apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  resources:
    - name: hello-world-repo
      type: git
    - name: hello-world-image
      type: image
  tasks:
    - name: build-hello-world
      taskRef:
        name: build-push-task
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/playground-git-input/hello-world #configure: may change according to your source
      resources:
        inputs:
          - name: playground-git-input
            resource: hello-world-repo
        outputs:
          - name: playground-image-output
            resource: hello-world-image
    - name: deploy-hello-world
      taskRef:
        name: deploy-hello-world
      resources:
        inputs:
          - name: source
            resource: hello-world-repo
          - name: image
            resource: hello-world-image
            from:
              - build-hello-world
      params:
        - name: path
          value: /workspace/source/tekton/deployment-hello-world.yml #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"